n = int(input('Digite um numero para ver sua tabuada: '))

print(f'____________')
print(f'1  X {n} = {n * 1}')
print(f'2  X {n} = {n * 2}')
print(f'3  X {n} = {n * 3}')
print(f'4  X {n} = {n * 4}')
print(f'5  X {n} = {n * 5}')
print(f'6  X {n} = {n * 6}')
print(f'7  X {n} = {n * 7}')
print(f'8  X {n} = {n * 8}')
print(f'9  X {n} = {n * 9}')
print(f'10 X {n} = {n * 10}')
print(f'____________')
